#!/bin/bash

echo "🎉 Testing Dynamic Email System - HR to Employee Direct Communication"
echo "=================================================================="
echo ""

# Check if LeaveEase is running
echo "ℹ️  Checking if LeaveEase application is running..."
if curl -s http://localhost:8080 > /dev/null; then
    echo "✅ LeaveEase application is running on http://localhost:8080"
else
    echo "❌ LeaveEase application is not running. Please start it first:"
    echo "   ./mvnw spring-boot:run"
    exit 1
fi

echo ""
echo "🎯 Dynamic Email System Features:"
echo "================================="
echo ""
echo "📧 NEW ENDPOINTS AVAILABLE:"
echo "• PUT http://localhost:8080/leaves/{id}/hr-approve - HR direct approval emails"
echo "• PUT http://localhost:8080/leaves/{id}/hr-reject - HR direct rejection emails"
echo "• POST http://localhost:8080/leaves/hr-email-config - Configure HR email credentials"
echo ""
echo "🔄 EMAIL ROUTING:"
echo "• OLD: System Email → Employee"
echo "• NEW: HR User Email → Employee (Direct Communication)"
echo ""
echo "✨ BENEFITS:"
echo "• Employees receive emails from actual HR person"
echo "• Employees can reply directly to HR user"
echo "• Professional AI-generated content"
echo "• Personal touch in communication"
echo ""
echo "🧪 TESTING INSTRUCTIONS:"
echo "========================"
echo ""
echo "📋 Step 1: Login to LeaveEase"
echo "1. Open browser: http://localhost:8080"
echo "2. Login with HR credentials:"
echo "   • Email: hr@company.com"
echo "   • Password: password123"
echo ""
echo "📋 Step 2: Test Dynamic Email System"
echo "Copy and paste this in browser console:"
echo ""
echo "// Test HR Direct Approval"
echo "fetch('/leaves', { method: 'GET' })"
echo ".then(response => response.json())"
echo ".then(data => {"
echo "    const pending = data.filter(leave => leave.status === 'Pending');"
echo "    if (pending.length > 0) {"
echo "        const leaveId = pending[0].id;"
echo "        console.log('🎯 Testing with leave ID:', leaveId);"
echo "        console.log('👤 Employee:', pending[0].employeeName);"
echo "        console.log('📧 Employee Email:', pending[0].employeeEmail || 'aastha@gmail.com');"
echo "        "
echo "        // Test HR direct approval"
echo "        return fetch(\`/leaves/\${leaveId}/hr-approve\`, {"
echo "            method: 'PUT',"
echo "            headers: { 'Content-Type': 'application/json' }"
echo "        });"
echo "    }"
echo "})"
echo ".then(response => response.json())"
echo ".then(data => {"
echo "    console.log('🎉 HR DIRECT EMAIL TEST RESULTS:');"
echo "    console.log('✅ Success:', data.success);"
echo "    console.log('📧 From Email:', data.fromEmail);"
echo "    console.log('📧 To Email:', data.toEmail);"
echo "    console.log('🤖 Email Method:', data.emailMethod);"
echo "    console.log('👤 HR User:', data.hrUser);"
echo "    console.log('📝 Message:', data.message);"
echo "    "
echo "    if (data.emailMethod === 'System Email (AI-powered)') {"
echo "        console.log('ℹ️  Note: Using system fallback. Configure HR email for direct communication.');"
echo "    } else {"
echo "        console.log('🎉 SUCCESS: Email sent directly from HR to Employee!');"
echo "    }"
echo "});"
echo ""
echo "📋 Step 3: Configure HR Email (Optional)"
echo "To enable direct HR-to-Employee emails:"
echo ""
echo "// Configure HR email credentials"
echo "fetch('/leaves/hr-email-config', {"
echo "    method: 'POST',"
echo "    headers: { 'Content-Type': 'application/json' },"
echo "    body: JSON.stringify({"
echo "        appPassword: 'your-gmail-app-password-here'"
echo "    })"
echo "})"
echo ".then(response => response.json())"
echo ".then(data => console.log('HR Email Config Result:', data));"
echo ""
echo "📋 Step 4: Test HR Rejection"
echo ""
echo "// Test HR direct rejection"
echo "fetch(\`/leaves/\${leaveId}/hr-reject\`, {"
echo "    method: 'PUT',"
echo "    headers: { 'Content-Type': 'application/json' },"
echo "    body: JSON.stringify({"
echo "        rejectionReason: 'Testing HR direct rejection email system'"
echo "    })"
echo "})"
echo ".then(response => response.json())"
echo ".then(data => {"
echo "    console.log('📋 HR REJECTION TEST RESULTS:');"
echo "    console.log('✅ Success:', data.success);"
echo "    console.log('📧 From Email:', data.fromEmail);"
echo "    console.log('📧 To Email:', data.toEmail);"
echo "    console.log('🤖 Email Method:', data.emailMethod);"
echo "    console.log('📝 Rejection Reason:', data.rejectionReason);"
echo "});"
echo ""
echo "🎯 EXPECTED RESULTS:"
echo "==================="
echo ""
echo "📧 System Fallback Mode (Default):"
echo "• emailMethod: 'System Email (AI-powered)'"
echo "• fromEmail: 'system'"
echo "• Professional AI-generated emails sent via system"
echo ""
echo "📧 HR Direct Mode (After Configuration):"
echo "• emailMethod: 'HR Direct Email'"
echo "• fromEmail: 'hr@company.com' (actual HR user email)"
echo "• Emails sent directly from HR user to employee"
echo ""
echo "🎨 EMAIL FEATURES:"
echo "=================="
echo ""
echo "✨ Approval Emails Include:"
echo "• Personalized greeting with employee name"
echo "• Complete leave details in professional format"
echo "• HR user contact information"
echo "• Pre-leave checklist with actionable items"
echo "• Beautiful HTML formatting"
echo "• Mobile-responsive design"
echo ""
echo "✨ Rejection Emails Include:"
echo "• Empathetic and understanding tone"
echo "• Clear rejection reason from HR"
echo "• Alternative suggestions and next steps"
echo "• HR contact info for direct discussion"
echo "• Encouragement to reapply with modifications"
echo ""
echo "🔧 GMAIL APP PASSWORD SETUP:"
echo "============================"
echo ""
echo "To enable HR direct emails:"
echo "1. Go to: https://myaccount.google.com/security"
echo "2. Enable 2-Factor Authentication"
echo "3. Click '2-Step Verification'"
echo "4. Scroll to 'App passwords'"
echo "5. Generate password for 'Mail'"
echo "6. Use the 16-character password in configuration"
echo ""
echo "🚀 SYSTEM STATUS:"
echo "================="
echo ""
echo "✅ Dynamic Email System: READY"
echo "✅ HR Direct Communication: AVAILABLE"
echo "✅ AI-Powered Content: ACTIVE"
echo "✅ System Fallback: WORKING"
echo "✅ Professional Templates: LOADED"
echo ""
echo "🎉 Your dynamic email system is ready for testing!"
echo "ℹ️  The system automatically chooses the best available email method"
echo ""
echo "🔗 Useful URLs:"
echo "• LeaveEase Application: http://localhost:8080"
echo "• HR Direct Approval: http://localhost:8080/leaves/{id}/hr-approve"
echo "• HR Direct Rejection: http://localhost:8080/leaves/{id}/hr-reject"
echo "• HR Email Config: http://localhost:8080/leaves/hr-email-config"
echo ""
echo "✅ Ready to test HR-to-Employee direct email communication!"